spring.application.name=lista-compras
spring.datasource.url=jdbc:postgresql://dpg-d81h0i57vvec73f3hc00-a:5432/listamercadodb
spring.datasource.username=admin
spring.datasource.password=BxCXXB3J8awdqI7EmNtspn80Uu0H4X4U

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect